# Generated by Django 3.1.4 on 2021-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default='0')),
                ('author', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
